baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Radar Bourse & Idées d’Investissement'
theme = 'ananke'
[params]
  custom_css = ["custom.css"]

[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
